apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-app-deploy
  namespace: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-app
  template:
    metadata:
      labels:
        app: webhook-app
    spec:
      containers:
      - name: webhook-app
        image: chaitanyachandra/webhook:arm_latest
        ports:
        - containerPort: 443
#        volumeMounts:
#        - name: webhook-certs
#          mountPath: "/app"
#          readOnly: true
#      volumes:
#      - name: webhook-certs
#        secret:
#          secretName: webhook-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: webhook-app
