apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai.fullname" . }}-service
  labels:
    {{- include "ai.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8091 # pod port
      protocol: TCP
  selector:
    {{- include "ai.selectorLabels" . | nindent 4 }}
