name: Test Workflow

on: workflow_dispatch

jobs:
  job-one:
    runs-on: ubuntu-latest
    env:
      string_one: "mynonprd"

    steps:
      - name: incident ticket
        if: ${{ contains(env.string_one, 'nonprd') || contains(env.string_one, 'sbx') }}
        run: echo "either conditions are true!"

      - name: Step with or condition
        if: ${{ !contains(env.string_one, 'nonprd' ) &&  !contains(env.string_one, 'sbx') }}
        run: echo "Both conditions are true!"