- name: jinja 2 template
  hosts: localhost
#  connection: local
  gather_facts: false
  vars:
    state: present
  tasks:
    - name: debug
      debug:
        msg: "{{ pools }}"
      vars:
        pools: "{{ groups.keys() }}"

    - name: generate file from shell
      shell: echo $(uname -a) >  file.txt
      args:
        chdir: "/tmp"
      delegate_to : node1.chaitu.net