- name: jinja 2 template
  hosts: localhost
#  connection: local
  gather_facts: false
  vars:
    state: present
  tasks:
    - name: debug
      debug:
        msg: "{{ pools }}"
      vars:
        pools: "{{ groups.keys() }}"

    - name: generate file from shell
      shell: echo $(uname -a) >  file.txt
      args:
        chdir: "/tmp"
      delegate_to : node1.chaitu.net

    - name: stat file
      stat:
        path: "/tmp/file.txt"
      delegate_to : node1.chaitu.net
      register: file_one

    - name: print file name      # sha1sum file.txt
      debug:
        msg: "{{ file_one.stat.checksum }}"


    - name: relace client ID and client secret
      block:
      - name: Replace clientSecret with blank
        replace:
          path: /tmp/file.yaml
          regexp: 'clientSecret:.*'
          replace: 'clientSecret: '

      - name: Replace clientID with blank
        replace:
          path: /tmp/file.yaml
          regexp: 'clientID:.*'
          replace: 'clientID: '
      delegate_to : node1.chaitu.net

    - name: Fetch the file from the remote machine
      fetch:
        src: /tmp/file.yaml
        dest: /tmp/file.yaml
        flat: yes
      delegate_to: node1.chaitu.net


    - name: Fetch the file from the remote machine
      shell: cat /tmp/file.yaml
      register: file_output

    - name: Fetch the file from the remote machine
      debug:
        msg: "{{ file_output }}"

    - name: copy file to remote michane
      copy:
        src: "{{ playbook_dir }}/inv.ini"
        dest: /tmp/files/inv.ini
      delegate_to: node1.chaitu.net

    - name: generate template file in  remote michane
      copy:
        src: "{{ playbook_dir }}/inv.ini"
        dest: /tmp/inv.ini
      delegate_to: node1.chaitu.net