---
# Q1
# k run po mc-pod -n mc-namespace --image=nginx:1-alpine --dry-run=client -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mc-pod
  name: mc-pod
  namespace: mc-namespace
spec:
  containers:
  - name: mc-pod-1
    image: nginx:1-alpine
  - name: mc-pod-2
    image: nginx:1-alpine
    command: ["sh", "-c"]
    args: |-
      while true; do
        sleep 1;
        echo $date >> /var/log/shared/date.log ;
      done
    volumeMounts:
    - mountPath:  /var/log/shared/
      name: volume-one
  - name: mc-pod-3
    image: nginx:1-alpine
    command: ["sh", "-c"]
    args: |-
      while true; do
        sleep 1;
        cat /var/log/shared/date.log ;
      done
    volumeMounts:
    - mountPath:  /var/log/shared/
      name: volume-one
  volumes:
  - name: volume-one
    emptyDir: {}