---
# Q1
# k run po mc-pod -n mc-namespace --image=nginx:1-alpine --dry-run=client -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mc-pod
  name: mc-pod
  namespace: mc-namespace
spec:
  containers:
  - name: mc-pod-1
    image: nginx:1-alpine
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
  - name: mc-pod-2
    image: nginx:1-alpine
    command: ["sh", "-c"]
    args:
    - while true;
      do
        sleep 1 ;
        echo "$(date)" >> /var/log/shared/date.log ;
      done
    volumeMounts:
    - mountPath:  /var/log/shared/
      name: volume-one
  - name: mc-pod-3
    image: nginx:1-alpine
    command: ["sh", "-c"]
    args:
    - while true ;
      do
        sleep 1 ;
        cat /var/log/shared/date.log j;
      done
    volumeMounts:
    - mountPath:  /var/log/shared/
      name: volume-one
  volumes:
  - name: volume-one
    emptyDir: {}
---
# k expose pod --port=6379 --name=messaging-service
# k create deploy hr-web-app --image=kodekloud/webapp-color --replicas=2
# k expose deployment  hr-web-app --port=30082 --target-port=8080 --name=hr-web-app-service

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
      path: /pv/data-analytics
---
kubectl autoscale deployment kkapp-deploy --cpu-percent=50 --min=1 --max=10
