apiVersion: v1
kind: Pod
metadata:
  name: tls-debug
  namespace: chaitanya
spec:
  restartPolicy: Never

  containers:
  - name: debug
    image: nicolaka/netshoot
    command: ["/bin/bash", "-c", "sleep infinity"]

    volumeMounts:
    - name: ca-cert
      mountPath: /certs
      readOnly: true

  volumes:
  - name: ca-cert
    secret:
      secretName: root-ca-secret
      items:
      - key: tls.crt
        path: my_app.crt
      - key: tls.key
        path: my_app.key