- name: seq
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
  tasks:
    - name: print first set using fact
      debug:
        msg: "{{ item }}"
      loop: "{{ groups['nodepool1'] }}"