- name: seq
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
  tasks:
    - name: print first set using fact
      debug:
        msg: "{{ item }}"
      loop: "{{ groups['nodepool1'] }}"
#    - name: generate template file
#      shell: ansible-playbook generate.yml -i inv.ini
    - name: sleep 10 mins
      pause:
        minutes: 10