from prometheus_client import CollectorRegistry, Gauge, push_to_gateway
import random
import time

push_gateway_url = 'http://<pushgateway-IP_address>:9091'
job_name = 'python_job'
instance_name = 'my_instance'
registry = CollectorRegistry()
random_metric = Gauge('random_metric', 'Random metric generated by Python script', ['label_name'], registry=registry)

value = random.randint(1, 100)
labels = {'label_name': 'example_label'}
random_metric.labels(**labels).set(value)  # Set a sample metric value

push_to_gateway(push_gateway_url, job=job_name, registry=registry, grouping_key={'instance': instance_name})
