- name: dict ref
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cluster: "cluster3"

    clusters_set_one:
      mainclusters: ["cluster1", "cluster2"]
      lb1: "node.kubernetes.io/microk8s-controlplane=microk8s-controlplane"

    clusters_set_two:
      mainclusters: ["cluster3", "cluster4"]
      lb1: "na=na"

  tasks:
    - name: Set fact based on cluster set
      set_fact:
        lb1_value: >-
          {% if cluster in clusters_set_one.mainclusters -%}
            {{ clusters_set_one.lb1 }}
          {% elif cluster in clusters_set_two.mainclusters -%}
            {{ clusters_set_two.lb1 }}
          {%- endif %}

    - name: Print the set fact value
      debug:
        msg: "{{ lb1_value }}"


#    - name: Print the value dynamically based on cluster
#      debug:
#        msg:
#          - "{{ vars[cluster]['lb1'] }}"



#    -  name: include dedicated node
#       include_tasks:
#         file: lb.yml