---
- name: Get all DaemonSets in the cluster
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
     daemon_sets:
      calico-node:
        namespace: "kube-systems"
        container: "calico-node"
        image: "docker.io/calico/node:v3.25.1"
      speaker:
        namespace: "metallb-system"
        container: "speaker" # kubectl get ds -n metallb-system  -o jsonpath="{.items[*].spec.template.spec.containers[*].name}"
        image: "quay.io/metallb/speaker:v0.13.3"
  tasks:
   -  name: include daemonset task
      include_tasks:
        file: ds_task.yml
      vars:
        k8s_ds_name : "{{ item.key }}"
        k8s_namespace: "{{ item.value.namespace }}"
        k8s_container: "{{ item.value.container }}"
        k8s_image: "{{ item.value.image }}"
      loop: "{{ daemon_sets | dict2items }}"

   - name: print
     debug:
       msg:
         - "{{ calico_node_response}}"
         - "{{ speaker_response}}"