- name: Get Kubernetes namespaces as a list
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    system_ns: ["kube-system", "kube-public", "kube-metrics-system"]

  tasks:
    - name: Get namespaces with label prm.managed=false
      k8s_info:
        api_version: v1
        kind: Namespace
        kubeconfig: "/Users/chaitanya/.kube/main/config"
        label_selectors:
          - "prm.managed=false"
      register: ns_output

    - name: Extract namespace names into a list
      set_fact:
        ns_list: "{{ ns_output.resources | map(attribute='metadata.name') | list }}"

    - name: Filter out excluded namespaces
      set_fact:
        filtered_ns: "{{ ns_list | difference(system_ns) }}"

    - name: Show final filtered namespaces
      debug:
        var: filtered_ns
