---
- name: Ensure kernel version is exactly as required
  hosts: "{{ my_hosts }}"
  gather_facts: true
  tasks:
    - name: Include kernal task
      ansible.builtin.include_tasks: kernal_task.yml

    - name: include os task
      ansible.builtin.include_tasks: os_version_check.yml
