---
- name: Ensure kernel version is exactly as required
  hosts: "{{ my_hosts }}"
  gather_facts: yes
  tasks:
    - name: Print current kernel version
      debug:
        msg: "Current kernel version is: {{ ansible_kernel }}, required kernel version {{ required_kernel_version }}"

    - name: set fact
      ansible.builtin.set_fact:
        response: "Current kernel version is: {{ ansible_kernel }}, required kernel version {{ required_kernel_version }}"
        cacheable: yes
      when: ansible_kernel != required_kernel_version

    - name: set fact
      ansible.builtin.set_fact:
        response: "insync"
        cacheable: yes
      when: ansible_kernel == required_kernel_version

    - name: Print
      debug:
        msg: "{{ response }}"