---
- name: Compare system clock synchronized and NTP status using regex_search
  hosts: all
  vars:
    system_clock_synchronized: "yes"
    ntp_service: "active"
    regex_system_clock_synchronized: "System clock synchronized: {{system_clock_synchronized}}"
    regex_ntp_service: "NTP service: {{ntp_service}}"
  tasks:
    - name: Get timedatectl status
      shell: timedatectl status
      register: timedatectl_output

    - name: Print extracted lines
      debug:
        msg:
          - "{{ timedatectl_output.stdout | regex_findall('System clock synchronized:.*') }}"
          - "{{ timedatectl_output.stdout | regex_findall('NTP service:.*') }}"
          - "{{ timedatectl_output.stdout | regex_search(regex_system_clock_synchronized) is not none }}"
          - "{{ timedatectl_output.stdout | regex_search(regex_ntp_service) is not none }}"

    - name: and
      debug:
        msg:
          - "{{ timedatectl_output.stdout | regex_findall('System clock synchronized:.*') }}"
          - "{{ timedatectl_output.stdout | regex_findall('NTP service:.*') }}"
      when: timedatectl_output.stdout | regex_search(regex_system_clock_synchronized) is not none and timedatectl_output.stdout | regex_search(regex_ntp_service) is not none
    - name: or
      debug:
        msg:
          - "{{ timedatectl_output.stdout | regex_findall('System clock synchronized:.*') }}"
          - "{{ timedatectl_output.stdout | regex_findall('NTP service:.*') }}"
      when: timedatectl_output.stdout | regex_search(regex_system_clock_synchronized) is none or timedatectl_output.stdout | regex_search(regex_ntp_service) is none
