apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ai-kustomize"},"name":"spec-service-kustomize-dev","namespace":"dev"},"spec":{"ports":[{"port":9201,"protocol":"TCP","targetPort":8800}],"selector":{"app":"ai-kustomize"}}}
  creationTimestamp: "2024-10-15T19:02:54Z"
  labels:
    app: ai-kustomize
  name: spec-service-kustomize-dev-two
  namespace: dev
  resourceVersion: "53777112"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9202
    protocol: TCP
    targetPort: 8800
  selector:
    app: ai-kustomize
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
