name: System Info Summary

on:
  workflow_dispatch:

  
jobs:
  get-timestamp:
    name: "📋 [1/2] Timestamp"
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.timestamp }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: execute tests
        id: execute_tests
        shell: bash
        run: |
          chmod +x ./shell/gh/code.sh
          bash ./shell/gh/code.sh