name: Persist Environment Variable

on:
  workflow_dispatch:

jobs:
  save-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Save a variable to a file
        run: echo "date='$date'" > my_variable.txt

      - name: Upload the variable as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: test1
          path: my_variable.txt

  load-variable:
    runs-on: ubuntu-latest
    needs: save-variable
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: test1

      - name: Load the variable from the file
        run: |
          source my_variable.txt
          echo "Loaded variable: $MY_PERSISTENT_VAR"
