name: System Info Summary

on:
  workflow_dispatch:

  
jobs:
  get-timestamp:
    name: "📋 [1/2] Timestamp"
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.timestamp }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: execute tests
        id: execute_tests
        shell: bash
        run: |
          chmod +x ./shell/gh/code.sh
          bash ./shell/gh/code.sh
    

  get-hostname:
    name: "📋 [2/2] Hostname"
    runs-on: ubuntu-latest
    needs: [get-timestamp]
    outputs:
      hostname: ${{ steps.hn.outputs.hostname }}

    steps:
      - name: Capture & append hostname row
        id: hn
        run: |
          HN=$(hostname)
          echo "hostname=$HN" >> "$GITHUB_OUTPUT"

          {
            echo -e "\n| Hostname | '$HN' | Success |"
          } >> "$GITHUB_STEP_SUMMARY"

          echo "✅ Hostname row appended: $HN"
