name: Test Workflow
on: workflow_dispatch
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: step-one
        run: echo hello
  job-two:
    runs-on: ubuntu-latest
    steps:
      - name: step-two
        run: exit 1
