name: Test Workflow
on: workflow_dispatch
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: step-one
        run: sleep 3 ; echo hello

  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    steps:
      - name: step-one
        run: exit 1

  job-three:
    runs-on: ubuntu-latest
    needs: job-two
    steps:
      - name: step-one
        run: sleep 3 ; echo hi
