name: Persist Environment Variable

on:
  workflow_dispatch:

jobs:
  save-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Save a variable to a file
        run: |
          current_date=`date`
          echo $current_date
          echo "snap_date='$current_date'" > vars.txt

      - name: Upload the variable as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: vars_test1
          path: vars.txt

  load-variable:
    runs-on: ubuntu-latest
    needs: save-variable
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: vars_test1

      - name: Load the variable from the file
        run: |
          source vars.txt
          echo `date`
          echo "Loaded variable: $snap_date"
